spring:
  application:
    name: license-plate-service

  datasource:
    url: jdbc:postgresql://localhost:5432/license_plate_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  Jackson:
    date-format: "yyyy-MM-dd HH:mm"
    time-zone: Europe/Minsk

logging:
  level:
    com.example.licenseplate: DEBUG
    com.example.licenseplate.service.cache: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"